### ISSUE TITLE
Maquetación de la web 

### ISSUE THREAD

**Issue by fran** [AsociacionDrupalES/DrupalCampEs#1]
La maquetación de la web.

**Comment by fran** [comment]
Hay que activar el módulo que @vengador implementó para el portal de inicio de la drupalcamp 2015.
El theme está integrado en el COD con el que se está montando el site.

Puntos a tener en cuenta:
1. Una vez se active el theme habrá que ajustar la maquetación.
2. Revisar si el theme para la administración y poner uno que sea claro.

**Comment by fran** [comment]
En mi fork he añadido a cod/themes el bootstrap y drupalcamp. Una vez haga el pullrequest y haga merge se podrá comenzar con la maquetación del site.

**Comment by fran** [comment]
Reasigno la tarea a @capynet

**Comment by capynet** [comment]
@fran le estoy dando amor  en general, opero si me dices alguna cosa en especial me enfoco en ella.

**Comment by fran** [comment]
@capynet su puedes dale amor a la come, que ya esta prácticamente lista.

**Comment by capynet** [comment]
Entonces pasame una db con esa home porque en mi local veo esto:

[image: Imágenes integradas 1]

Saludos!

2015-02-25 8:31 GMT+01:00 Francisco José Seva mora <notifications@github.com

**Comment by capynet** [comment]
Pasame tu db porfa así lo veo también :)

**Comment by capynet** [comment]
La web en general mas o menos tiene forma. Voy a dar por cerrado este issue para dejar lugar a issues mas específicos.
