### ISSUE TITLE
Mollom se las come con patatas

### ISSUE THREAD

**Issue by DavidHernandez** [AsociacionDrupalES/DrupalCampEs#105]
Mollom no está previniendo bien los registros de usuarios:
http://2015.drupalcamp.es/es/user/320/edit
http://2015.drupalcamp.es/es/user/318/edit

¿Podemos revisar la configuración de Mollom o buscar una alternativa?

**Comment by capynet** [comment]
Revisé la conf de mollom y estaba todo en orden. Habilité una opción extra de análisis para tratar de cazar mas bots, pero nunca antes la usé por lo que no se que eficacia tenga. 

Si a lo largo de estos días nos vemos que mollom no está a la altura probamos otras alternativas.

**Comment by capynet** [comment]
Elimino todos los bots.
