### ISSUE TITLE
Revisar las URLs de las sesiones

### ISSUE THREAD

**Issue by lurish** [AsociacionDrupalES/DrupalCampEs#121]
Hola,

Las URLs de las ponencias deberían tener el título de la misma y no "/node/num_node".

Ejemplos en los que pasa: 
http://2015.drupalcamp.es/node/111
http://2015.drupalcamp.es/node/152
http://2015.drupalcamp.es/node/155
http://2015.drupalcamp.es/node/162

Uno en el que no pasa (está bien):
http://2015.drupalcamp.es/es/sessions/pensando-en-big-data

Gracias,

**Comment by jsbalsera** [comment]
Es decir, que solo tienen path creado en castellano.

**Comment by lurish** [comment]
Si tuvieran path en castellano todas, esta también debería tener la URL ok: http://2015.drupalcamp.es/node/162

**Comment by DavidHernandez** [comment]
Esa sesión si tiene URL en castellano: http://2015.drupalcamp.es/es/sessions/cuando-dev-encontr%C3%B3-ops

Hace falta instalar Global Redirect para forzar el uso del alias: https://www.drupal.org/project/globalredirect

**Comment by lurish** [comment]
Ok ;)

**Comment by NITEMAN** [comment]
@DavidHernandez para la futura distro de las camps... ya posíais añadir también transliteration

Que siemrpe uso acentos en lso títulos de mis charlas XD
