### ISSUE TITLE
Social network block

### ISSUE THREAD

**Issue by monfranco** [AsociacionDrupalES/DrupalCampEs#124]
We need to have icons linked to flickr, facebook, twitter and vimeo.
The most important is to have flickr and vimeo

**Comment by jsbalsera** [comment]
perhaps a menu showed as a block, like asociaciondrupal.es?

**Comment by monfranco** [comment]
this website doesn't have the menu block module. In my opinion, we can create a block only with text linked to the social networks.

**Comment by DavidHernandez** [comment]
Moving this to 2016 goals.
