### ISSUE TITLE
English Menu

### ISSUE THREAD

**Issue by jsbalsera** [AsociacionDrupalES/DrupalCampEs#138]
- The menu shows a bullet list.
- it shows a title "Main menu EN"

**Comment by isholgueras** [comment]
It seems that two blocks (eng & spa) has different HTML.

Te solution could be adding the id "block-system-main-menu" at  block container and adding a wrapper div with class "inner-content" like this:
![en-menu](https://cloud.githubusercontent.com/assets/140742/12912584/cb09b898-cf19-11e5-905b-3e70a327c4c8.png)

**Comment by capynet** [comment]
Solucionado. Lo despliego en un rato.
