### ISSUE TITLE
Necesitamos las url de twitter y facebook para ponerlas en los link al lado del main menu

### ISSUE THREAD

**Issue by capynet** [AsociacionDrupalES/DrupalCampEs#142]

**Comment by DavidHernandez** [comment]
https://twitter.com/drupalcampspain
https://www.facebook.com/DrupalCampSpain/

**Comment by mgzrobles** [comment]
hay que ocultar el texto del link 
![image](https://cloud.githubusercontent.com/assets/1476394/13050469/d0ae2610-d3f3-11e5-8649-1d35421f74d3.png)

**Comment by capynet** [comment]
Fue temporal, estaba desplegando :)
