### ISSUE TITLE
Delete the old and unused drupalcamp profile

### ISSUE THREAD

**Issue by DavidHernandez** [AsociacionDrupalES/DrupalCampEs#145]
The DrupalCamp old profile is no longer used and it can be removed: https://github.com/AsociacionDrupalES/DrupalCampEs/tree/master/profiles/drupalcamp

All the development is handled in the COD profile.

**Comment by Saphyel** [comment]
Pantheon profile and drupalcamp is not used or called outside of the profile.

**Comment by capynet** [comment]
Todo parece seguir funcionando. Gracias!
