### ISSUE TITLE
En el bloque de sponsors gold hay un link que apunta a 404

### ISSUE THREAD

**Issue by capynet** [AsociacionDrupalES/DrupalCampEs#150]

**Comment by capynet** [comment]
El nodo existe pero está despublicado hasta que se apruebe el presupuesto de los patrocinios.

node/34/edit

**Comment by mgzrobles** [comment]
los links de los sponsors plata van todos a 404
¿rutas erróneas?
en la página de 404 se incluyen los patrocinadores y son distintas...
ejemplo de links en http://2016.drupalcamp.es/es/drupalcamp-spain-2015/sponsors: 
http://2016.drupalcamp.es/es/biko2.com dirige a 404
en dicha página el link es distinto y funciona http://2016.drupalcamp.es/es/sponsors/biko2

**Comment by marcoscano** [comment]
Acabo de revisar esta issue.

Ambos links rotos en el bloque de Gold Sponsors tienen redirects que van a nodos actualmente no publicados (33 y 34). Cuando se resuelva #156 y se publiquen estos nodos, esto ya no ocurrirá.

Sobre los links en los patrocinios plata, no he podido reproducir el problemas (los links están bien), así que supongo que ya se habrá resuelto.
