### ISSUE TITLE
opengraph sigue mostrando la del 2015

### ISSUE THREAD

**Issue by capynet** [AsociacionDrupalES/DrupalCampEs#152]
og:site_name: DrupalCamp Spain 2015
og:title: DrupalCamp Spain 2015
og:image: http://2016.drupalcamp.es/sites/default/files/logo-drupalcamp.png

mision search and destroy

**Comment by fran** [comment]
I have found site name was Drupal Camp 2015  and I changed to use 2016. Reviewing variables I found the message displayed when the site is in maintain mode was using 2015, so I changed too.

What do you mean with image? Not sure what is supposed to be modified
/cc @capynet

**Comment by capynet** [comment]
Solucionado.
