### ISSUE TITLE
Prepare data for the mobile app

### ISSUE THREAD

**Issue by DavidHernandez** [AsociacionDrupalES/DrupalCampEs#154]
The app will load the data using a JSON. The required structure is:

{
  "speakers": [ {
    "name":"Speaker name",
    "company":"Company",
    "twitter":"@nick",
    "image":"http://blablabla.com/image.jpg"
  }],
  "sessions": [{
    "name":"Session title",
    "date":"23/04/2016 10:00:00",
    "room":1,
    "speaker":"@nick"
  }]
}

**Comment by capynet** [comment]
Se la vamos a poder pasar la info cuando se cierren los call for paper. a la espera quedamos.

**Comment by marcoscano** [comment]
Do they need a services endpoint or a dump file?

**Comment by DavidHernandez** [comment]
No, a dump file should fine. But better if is something we can easily re-use in next years.

**Comment by marcoscano** [comment]
If we want to re-use this I think the best is to create an endpoint. The PR https://github.com/AsociacionDrupalES/DrupalCampEs/pull/175 accounts for this.

Steps to test:

Enable the feature and all its dependencies:
drush en aed_services_feature

Call the services at:
$ curl -i -H "Content-Type: application/json" -X GET http://dcamp.localhost/api/v1/sessions
$ curl -i -H "Content-Type: application/json" -X GET http://dcamp.localhost/api/v1/speakers

**Comment by marcoscano** [comment]
Notes:
The structure needed requested for some details (session date / room) that are not referenced on the session nodes themselves. This needs to be updated when we know how this is going to be represented / linked to the session contents.

To update this, go to
profiles/cod/modules/custom/aedcamp_resources/aedcamp_resources.inc
lines 31 and 32

**Comment by DavidHernandez** [comment]
Reducer priority until the sessions are selected.

**Comment by capynet** [comment]
El PR está aceptado. Hablando con @marcoscano quedamos en que nos hecha una mano habilitandolo y poniendolo a funcionar. @ccamposfuentes Es el que ha hecho la aplicación.- Ya le he pasado la charla que tuve con marcos para que esté al tanto y puedan interoperar.

**Comment by capynet** [comment]
Ya está atendido este asunto.
