### ISSUE TITLE
Add length of session to the sessions form

### ISSUE THREAD

**Issue by DavidHernandez** [AsociacionDrupalES/DrupalCampEs#155]
We talked about having the chance to specify the length of the session: light talk (5m), session (45m) and workshop (2h?). The field should be able to accept multiple fields, so the speaker can specify that he can do the session in different formats if required.

**Comment by capynet** [comment]
Mergeado el PR y funcionando. Gracias.

**Comment by DavidHernandez** [comment]
This doesn't appear on the site.

**Comment by DavidHernandez** [comment]
I think is getting pretty late to do this. We have only 9 days until the call4papers ends and we can't move this properly. So we have to forget about the lightning talks and the workshops during the event.
