### ISSUE TITLE
Some blocks are not translatable

### ISSUE THREAD

**Issue by DavidHernandez** [AsociacionDrupalES/DrupalCampEs#157]
For example, the one with the text to propose a session: http://2016.drupalcamp.es/en/admin/structure/block/manage/block/5/configure?destination=home

**Comment by mbarcia** [comment]
Yo veo traducible (y traducido en portada) este bloque (ID 5).

![captura de pantalla 166](https://cloud.githubusercontent.com/assets/6518569/13028754/efe28bba-d278-11e5-9f9c-aaa2682f18f1.png)

Ideas?

**Comment by mbarcia** [comment]
Esto lo obtengo en mi local, desplegando la rama de #167 con Drupsible. No puedo comprobarlo en PROD, no tengo las credenciales.

**Comment by capynet** [comment]
Puntualmente ese bloque veo que ya lo han traducido, ergo está resuelto :)
