### ISSUE TITLE
Problemas de frontend en las páginas de sesiones

### ISSUE THREAD

**Issue by DavidHernandez** [AsociacionDrupalES/DrupalCampEs#160]
El interlineado en los títulos de sesión largo es demasiado pequeño.

Ejemplo: http://2016.drupalcamp.es/en/sessions/forget-about-multiple-rest-requests-enter-restful

**Comment by DavidHernandez** [comment]
En ese mismo tipo de página, las imágenes en el body no se adaptan al dispositivo.

**Comment by DavidHernandez** [comment]
Ejemplo: https://monosnap.com/file/ElesyXAWoHovHY6GuXRu4ss6Z4no6h#

**Comment by capynet** [comment]
Solucionado.
