### ISSUE TITLE
Los usuarios anonimos pueden editar sesiones propuestas

### ISSUE THREAD

**Issue by capynet** [AsociacionDrupalES/DrupalCampEs#170]
Ejemplo: http://2016.drupalcamp.es/en/sessions/forget-about-multiple-rest-requests-enter-restful

![forget about multiple rest requests enter restful drupalcamp spain 2016](https://cloud.githubusercontent.com/assets/1402913/13049443/44016b9c-d3ed-11e5-8259-df98cd94877a.png)

**Comment by mgzrobles** [comment]
seguro? he probado como anónimo y no veo los botones e intentando acceder a la página de edición sale que te logues para ver la página

**Comment by capynet** [comment]
Es verdad, ahora yo tampoco puedo reproducirlo. Se me habrá ido la cabeza y estaría logueado....
