### ISSUE TITLE
Make the session description mandatory

### ISSUE THREAD

**Issue by DavidHernandez** [AsociacionDrupalES/DrupalCampEs#171]
Right now is possible to create session propossals without a description. That's an error and should be changed to mandatory.

**Comment by marcoscano** [comment]
https://github.com/AsociacionDrupalES/DrupalCampEs/pull/176

**Comment by capynet** [comment]
Aquí me he perdido, @marcoscano hiciste un PR?

**Comment by capynet** [comment]
Ya no tiene sentido :(
