### ISSUE TITLE
Translate speakers guide page

### ISSUE THREAD

**Issue by DavidHernandez** [AsociacionDrupalES/DrupalCampEs#172]
This page is currently only in spanish: http://2016.drupalcamp.es/en/node/3

**Comment by juampynr** [comment]
@DavidHernandez, the translation is at http://2016.drupalcamp.es/en/content/speaker-guidelines. I don't have permissions to adjust this at http://2016.drupalcamp.es/en/admin/structure/menu/manage/main-menu so it shows up.

**Comment by DavidHernandez** [comment]
There are two different menus, so we need to add the english nodes to the english main menu and the spanish nodes to the spanish main menu.

English menu: http://2016.drupalcamp.es/en/admin/structure/menu/manage/menu-main-menu-en
Spanish menu: http://2016.drupalcamp.es/en/admin/structure/menu/manage/main-menu

**Comment by juampynr** [comment]
:+1:
