### ISSUE TITLE
Sponsors page has issues

### ISSUE THREAD

**Issue by juampynr** [AsociacionDrupalES/DrupalCampEs#178]
The Spanish version has an unrelated body text:

![image](https://cloud.githubusercontent.com/assets/108130/13109523/09b1aca2-d57a-11e5-9a0b-18bd1e509797.png)

The English version takes to a 404:

![image](https://cloud.githubusercontent.com/assets/108130/13109533/1ab9dfc4-d57a-11e5-9f40-d2d14e753910.png)

**Comment by plopesc** [comment]
I updated the URL in the view to move form 2015 to 2016.
I have to consolidate the changes in features, but I'll setup a local environment tomorrow.
closing for now.

**Comment by juampynr** [comment]
:+1:
