### ISSUE TITLE
Some session description don't show up

### ISSUE THREAD

**Issue by DavidHernandez** [AsociacionDrupalES/DrupalCampEs#179]
Here is a session with a small description that doesn't show up when viewing it: http://2016.drupalcamp.es/en/sessions/apps-no-nativas-drupal-8

**Comment by plopesc** [comment]
I just checked some other sessions and *none* of them are showing the description:
http://2016.drupalcamp.es/en/sessions/hoy-estoy-muy-ansible
http://2016.drupalcamp.es/en/sessions/da-vinci-8

I think this is a regression. There was an already fixed ticket for this.
Any idea?

**Comment by marcoscano** [comment]
As we just commented on IRC, this content type was wrongly panelized. Disabling the panelizer for this content type solves the issue
