### ISSUE TITLE
Problemas con  contrib/aedcamp

### ISSUE THREAD

**Issue by fran** [AsociacionDrupalES/DrupalCampEs#18]
En cod.info hemos definido la dependencia
; AED Customizations
dependencies[] = aedcamp

que está causando un error en el momento de instalación (he probado la instalación con la dependencia comentada y sin comentar. En el primer caso la instalación es correcta y en el segundo no). Adjunto una imagen con el error.
![selection_050](https://cloud.githubusercontent.com/assets/14607/6204712/2b944a24-b554-11e4-8d12-27ba04573d5c.png)

**Comment by DavidHernandez** [comment]
Ok, this issue should be fixed in this PR: https://github.com/AsociacionDrupalES/DrupalCampEs/pull/19

**Comment by fran** [comment]
Yeaaahh

**Comment by fran** [comment]
Fixed by the great David Hernandez :p
