### ISSUE TITLE
Traducir los alojamientos a inglés

### ISSUE THREAD

**Issue by capynet** [AsociacionDrupalES/DrupalCampEs#183]
Español: node/5 

Hay que poner en node/16 lo mismo que en el node 5 pero en inglés

**Comment by ignaciosegura** [comment]
Me pongo a ello. No puedo asignarme tareas en este repositorio, pero se puede contar con que yo me encargo.

**Comment by juampynr** [comment]
Traducido http://2016.drupalcamp.es/en/content/accommodation

**Comment by juampynr** [comment]
Añadido al menú. Cierro.

![image](https://cloud.githubusercontent.com/assets/108130/13220715/e4fc5ac2-d977-11e5-8ddb-f589beb27de0.png)
