### ISSUE TITLE
Añadir imágenes de cada alojamiento a la derecha

### ISSUE THREAD

**Issue by capynet** [AsociacionDrupalES/DrupalCampEs#184]
Para mejorar un poco el contenido estaría bien tener una imagen que acompañe los datos de cada hotel como se hizo en la del año pasado: [http://2015.drupalcamp.es/es/drupalcamp-spain-2015/informacion/alojamiento](http://2015.drupalcamp.es/es/drupalcamp-spain-2015/informacion/alojamiento)

**Comment by casanova347** [comment]
Hecho!
