### ISSUE TITLE
Traducir al inglés la pagina de transportes.

### ISSUE THREAD

**Issue by capynet** [AsociacionDrupalES/DrupalCampEs#185]
Es el nodo 8 y la traducción debe ir en el nodo 23

**Comment by ignaciosegura** [comment]
Me pongo a ello. No puedo asignarme tareas en este repositorio, pero se puede contar con que yo me encargo.

**Comment by juampynr** [comment]
Hecho 
![image](https://cloud.githubusercontent.com/assets/108130/13221604/8b8fbbe6-d97c-11e5-8900-ffe04c09a54c.png)

@capynet, hay un par de frases en el nodo en español del tipo "más info aquí" que no tienen enlace. Cuando añadáis enlaces, acordáos de ponerlos también en la traducción.
