### ISSUE TITLE
Maquetar la order

### ISSUE THREAD

**Issue by capynet** [AsociacionDrupalES/DrupalCampEs#190]
Cuando compras una entrada puedes ver tu order desde tu perfil. Se ve fatal.

**Comment by Saphyel** [comment]
Por aqui es muy comun delegar el tema de compra de entradas a 3s, por lo que te libras del tema de gestion/compra/etc... (se que ahora es tarde, pero para la proxima camp yo creo que es una opcion a tener en cuenta...)

**Comment by DavidHernandez** [comment]
Esa parte ya está gestionada. Actualmente ya se pueden comprar entradas
para terceros.

**Comment by capynet** [comment]
Hola, gracias a los dos pero este issue solo habla de que la maquetacion de una sección está mal :D

**Comment by capynet** [comment]
Hecho,
