### ISSUE TITLE
Menú no responde en iPad

### ISSUE THREAD

**Issue by ignaciosegura** [AsociacionDrupalES/DrupalCampEs#191]
El menú principal no responde en iPad, sin importar la orientación. Los links a secciones no responden.

En orientación vertical, además, éste se puede desplegar, aunque el resultado visual es extraño.

**Comment by capynet** [comment]
Adjunta una captura por favor. Preferiblemente en vertical y horizontal

**Comment by ignaciosegura** [comment]
![simulator screen shot 4 mar 2016 14 47 16](https://cloud.githubusercontent.com/assets/10077661/13528720/38904952-e218-11e5-8b8f-bd43caa0a71d.png)
![simulator screen shot 4 mar 2016 14 47 26](https://cloud.githubusercontent.com/assets/10077661/13528722/3895fc8a-e218-11e5-95f7-62bc63ae85b9.png)
![simulator screen shot 4 mar 2016 14 47 59](https://cloud.githubusercontent.com/assets/10077661/13528721/389239b0-e218-11e5-87e4-673dcd2c94c2.png)
![simulator screen shot 4 mar 2016 14 48 04](https://cloud.githubusercontent.com/assets/10077661/13528723/38dac644-e218-11e5-8c4f-3605ecf2ab14.png)

**Comment by ignaciosegura** [comment]
![simulator screen shot 4 mar 2016 14 50 31](https://cloud.githubusercontent.com/assets/10077661/13528769/80849b6e-e218-11e5-9f60-2ac3d960c1de.png)

**Comment by casanova347** [comment]
Solucionado
