### ISSUE TITLE
Fix attendees view

### ISSUE THREAD

**Issue by jsbalsera** [AsociacionDrupalES/DrupalCampEs#194]
The attendees view are not showing any user.

**Comment by jsbalsera** [comment]
The Business Day attendees display is there: https://github.com/AsociacionDrupalES/DrupalCampEs/pull/196

The tickets for the Business Day need to be changed to complete where appropriate. Of course the PR would also need the feature to be reverted.

**Comment by capynet** [comment]
Implementado. grazie mille!
