### ISSUE TITLE
Mover el cambio de idioma a top right absolute en desk

### ISSUE THREAD

**Issue by capynet** [AsociacionDrupalES/DrupalCampEs#201]
Nos quedamos sin espacio en la zona de navegación. Hay que mover el bloque a la posición que he marcado en la imagen adjunta.

![screenshot from 2016 04 14 12 02 30](https://cloud.githubusercontent.com/assets/1402913/14524491/e60ab262-0238-11e6-913c-1342ef235189.png)

Creo que con CSS solo se puede acomodar.

**Comment by DavidHernandez** [comment]
Solución fácil, poner en el menú algo como "Camp", con una noticia o cualquier cosa y dentro de este menú, meter como submenú: Asistentes, Business Day, Calendario de sesiones y Sprints.

**Comment by DavidHernandez** [comment]
Resuelto.
