### ISSUE TITLE
Sistema de ventas de entradas

### ISSUE THREAD

**Issue by fran** [AsociacionDrupalES/DrupalCampEs#3]
Implementar el sistema de ventas de entradas teniendo en cuenta que acepte cupones de descuento.

**Comment by fran** [comment]
Estoy con este tema

**Comment by DavidHernandez** [comment]
Esto ya ha sido testeado y funciona bien. Habrá que configurar los detalles de acceso al hacer los deploys porque no se quiere exportar ni que los detalles de la AED aparezcan en el código.
