### ISSUE TITLE
Theming: Implementar en la web el slider que está en la landing 

### ISSUE THREAD

**Issue by capynet** [AsociacionDrupalES/DrupalCampEs#39]
es un view. no se si está en la web de la camp. en todo caso se lo pedimos a @vengador para que nos lo pase o nos de acceso a la landing así podemos exportarlo con features.

**Comment by capynet** [comment]
Si quieres pasame este issue @fran pero decime donde encontrarlo que no veo el view :)

**Comment by fran** [comment]
@capynet no lo tenía subido. Te he enviado por correo la feature de la actual web.

**Comment by vengador** [comment]
Done!
