### ISSUE TITLE
Crear listado de sesiones propuestas

### ISSUE THREAD

**Issue by fran** [AsociacionDrupalES/DrupalCampEs#40]
En la url sessions, habrá un listado con las sessiones propuestas de forma que se mostrará la siguiente información:

* título 
* descripción
* nivel (beginer, advanced, ...)
* speaker

Las sesiones que se listarán serán aquellas con estado published (tener en cuenta que published no es accepted).

Una vez se tenga la vista, habrá que enlazarla en la entrada de menú correspondiente (tener en cuenta que las entradas de menú están creadas en código en aedcamp.install).

**Comment by fran** [comment]
Ready to test

**Comment by DavidHernandez** [comment]
@luismagr ¿Puedes crear un pull request con el cambio? He intentado aplicar el parche de tu commit pero ya no aplica. ¿Puedes adaptarlo a la última versión del código?

**Comment by DavidHernandez** [comment]
Ok, este cambio ya fue mergeado a dev: https://github.com/AsociacionDrupalES/DrupalCampEs/pull/41

Y como fue mergeado hace tiempo, ha ido a producción en el lanzamiento de la web.

Cuando tenga un ratejo, lo reviso, para ver si lo podemos poner como activo.

**Comment by keopx** [comment]
@fran yo cree la sesiones con un listado de propuesta y aceptadas para filtrarlas. Por defecto Propuesta.

Utilice field_permission para que los que la subian no pudiesen ver ni modificar ese campo. Hice la view para propuestas.

Cuando se aceptaron cambie ese valor y cambie la vista el valor a filtrar y listo
