### ISSUE TITLE
Añadir botón de registro de usuario.

### ISSUE THREAD

**Issue by capynet** [AsociacionDrupalES/DrupalCampEs#52]
En la parte superior derecha de la cabecera. (Aprovechar el menu de usuario que ya está colocado.)

**Comment by fran** [comment]
@capynet para esta tarea necesitas un bloque donde esté el link? Si hace falta backend o configuración hazme ping que yo lo hago.

**Comment by fran** [comment]
El link al registro es 

http://drupalcamp.dev.d4dev.com/es/drupalcamp-spain-2015/registration

**Comment by fran** [comment]
He creado un bloque con imagen y otro sin imagen y est'an puestos.
