### ISSUE TITLE
Crear paquetes de sponsors bajo el item de menu "sponsors"

### ISSUE THREAD

**Issue by capynet** [AsociacionDrupalES/DrupalCampEs#54]
Poner este contenido http://2014.drupalcamp.es/sponsor-packages.html y avisar a mon_franco para que lo actualice.

**Comment by fran** [comment]
Yo cree la entrada patrocinios aka sponsorships, esta tarea se refiere a eso, no?

**Comment by fran** [comment]
Está pendiente poner la información.

**Comment by fran** [comment]
Done
