### ISSUE TITLE
Dejar bien claro en la venta de entradas la posibilidad de ser socio.

### ISSUE THREAD

**Issue by capynet** [AsociacionDrupalES/DrupalCampEs#55]
Tal vez una imagen tipo [ticket de entrada] + [logo de la aed] = 30€. Esto al lado de la venta tradicional de entrada.

**Comment by fran** [comment]
Temporalmente he creado un pequeño bloque en el menú de navegación y otro con una imagen que he pillado de google indicando Sign up.

**Comment by capynet** [comment]
@fran no te sigo, ese comentario es parte del issue?

**Comment by fran** [comment]
@capynet  confundí con la issue del registro de usuarios. Sorry :S

**Comment by monfranco** [comment]
Y poner también el 21% de iva en las entradas

**Comment by capynet** [comment]
Esto ha quedado un poco obsoleto ya

**Comment by monfranco** [comment]
Esto esta hecho ;)
