### ISSUE TITLE
Revisar maquetación de la página de asistentes

### ISSUE THREAD

**Issue by DavidHernandez** [AsociacionDrupalES/DrupalCampEs#63]
Cuando el tamaño de la ventana se reduce, parte de los resultados de la vista de asistentes queda detrás del sidebar derecho:
![attendees](https://cloud.githubusercontent.com/assets/877002/6662901/2b52dd04-cbc1-11e4-9c55-d736edda30ed.png)

**Comment by vengador** [comment]
Buenas @DavidHernandez,

¿En qué navegador lo probaste? He estado intentando reproducir el issue pero no he podido :(

**Comment by DavidHernandez** [comment]
Parece ser que alguien ya lo ha resuelto :)
