### ISSUE TITLE
Añadir cupones de descuento

### ISSUE THREAD

**Issue by DavidHernandez** [AsociacionDrupalES/DrupalCampEs#65]
Es necesario que añadamos un sistema para aceptar cupones de descuento (para miembros de la AED, estudiantes y lo que la organización considere pertinente...).

Esta tarea está bloqueando esta otra, de la web de la AED: https://github.com/AsociacionDrupalES/asociaciondrupal/issues/46

**Comment by fran** [comment]
Solo haría falta activar los módulos y configurarlos con los precios.  Por otra parte necesitaría saber el descuento de cada uno de los cupones.

**Comment by DavidHernandez** [comment]
¿Lo has testeado? ¿Se pueden crear cupones en "batch" para poder crear 
cupones únicos para cada sponsor? Me suena a mi que no iba muy bien el 
tema el año pasado.

**Comment by fran** [comment]
He creado un cupón de prueba pero no he visto qnue se puedean hacer en batch. Habría que hacerlo uno a uno si se quier un cupon por sponsor. 
Le voy a dar una vuelta más al módulo para ver si se puede hacer.

**Comment by DavidHernandez** [comment]
La generación en batch se hace con otro módulo: 
https://www.drupal.org/project/commerce_coupon_batch

Y por lo que veo, sigue sin haberse actualizado, por lo que supongo que 
sigue sin ir.

De todos modos, como ahora COD permite comprar varias entradas 
simultáneamente, igual no es un problema. Eso si, para los speakers, 
habrá que comprarles las entradas a mano, para tener que evitar crear 
todos los cupones a mano.

**Comment by DavidHernandez** [comment]
I'm closing this as we already have the coupons working.
