### ISSUE TITLE
Crear página de créditos

### ISSUE THREAD

**Issue by DavidHernandez** [AsociacionDrupalES/DrupalCampEs#66]
Es necesario crear una página de créditos o agradecimientos para nombrar a la gente implicada en la organización de la DrupalCamp. También hay que eliminar la sección de colaboradores de la página de sponsors

**Comment by fran** [comment]
Me pongo con esto mañana. Si alguien se puede poner antes que se autoasigne la tarea.

**Comment by fran** [comment]
Estoy con esta tarea. Lo que seguro que me hará falta es alguien que lo maquete :]

**Comment by fran** [comment]
He subido una feature con la vista. Está pendiente la maquetación. Me desasigno la tarea para que el maquetador se la asigne. Una vez tengamos el listado terminado actualizaré el profile de instalación.

**Comment by DavidHernandez** [comment]
@keilovecraft, ¿podemos generar los archivos CSS y añadirlos también al repo? Ya que estos no se compilan automáticamente.

**Comment by DavidHernandez** [comment]
Ok, ha quedado demostrada mi ignorancia. Drupal se encarga de generar los archivos CSS a partir de los archivos de Less.

Gracias @keilovecraft!

**Comment by keilovecraft** [comment]
Subí los estilos, y cambios tanto en Views como en nuevos presets de imagenes.

Drupal compila los archivos con el módulos Less CSS Preprocessor y los mete en sites/default/files/less, mientras esté activado eso... todo debería rodar :)

**Comment by DavidHernandez** [comment]
Testeados los cambios de @keilovecraft. Todo pinta bien. Solo he añadido lo que faltaba para activar la nueva feature automáticamente. He usado el hook_update_7019 porque el 7018 ya lo he usado en otra issue: #40 

Por tanto, supongo que habrar que mergear antes la issue #40
