### ISSUE TITLE
Añadir bloque de login y/o fácil acceso al registro

### ISSUE THREAD

**Issue by DavidHernandez** [AsociacionDrupalES/DrupalCampEs#68]
Ahora mismo no hay ningún acceso al login ni a la página de registro. Pero para enviar una sesión es necesario estar registrado. ¿Podemos arreglarlo?

**Comment by DavidHernandez** [comment]
He visto que si que hay un bloque con una imagen. ¿Podemos hacerlo más visible? ¿Tal vez añadiendo un título?

**Comment by keopx** [comment]
@DavidHernandez  le propuse a @fran usar como en el DDAY un bloque para el registro y envio de sesiones, que si no estas autentucado te envie a registrarte.

**Comment by keopx** [comment]
@fran puede verse aqui: https://github.com/AsociacionDrupalES/DrupalDay/tree/master/sites/all/modules/custom

**Comment by capynet** [comment]
Ahora mismo entre el bloque de "Registrate" y el link que hay en la parte derecha superior del header, esta necesidad queda cubierta. Cierro!
