### ISSUE TITLE
Implementar la sección para los features speakers

### ISSUE THREAD

**Issue by fran** [AsociacionDrupalES/DrupalCampEs#7]
En la drupalcamp 2014 había un TOC para speaker y un block. Revisar si se pueden reutilizar (features).

**Comment by fran** [comment]
@luismagr quiere ponerse con esta tarea.

**Comment by fran** [comment]
COD by default does not have an speaker rol. We could create one and set it to get the users in the block or get the user related to the accepted session.
In COD speaker are user attendee related to an accepted session.

**Comment by fran** [comment]
Está pendiente testearlo pero por ahora esta tarea queda despriorizada hasta que la web salga a producción.

**Comment by fran** [comment]
Ready to test

**Comment by fran** [comment]
The page is created in live but needs the reference to the sessions. 
Pending tasks:

1. Create the featured speaker sessions.
2. Link the sessions in the featured speakers list.

**Comment by fran** [comment]
Está pendiente crear la sesión de Ricardo ya que no encuentro la información en el documento.
Hago ping en el hilo del grupo.

**Comment by fran** [comment]
He creado la sesión para Ricardo con un título privisional
http://2015.drupalcamp.es/es/sessions/seguridad-en-php

**Comment by capynet** [comment]
que onda esto? hay que crear el bloque de features speakers? si me lo confirman la hago yo.

**Comment by capynet** [comment]
Done
