### ISSUE TITLE
Review responsiveness on iPhones

### ISSUE THREAD

**Issue by DavidHernandez** [AsociacionDrupalES/DrupalCampEs#70]
Seems that the theme is broken when browsing the website using iThings: https://s3-eu-west-1.amazonaws.com/uploads-eu.hipchat.com/128746/934491/RRdLbu2TyEDvcKZ/upload.png

Can this be reviewed and fixed?

**Comment by DavidHernandez** [comment]
Seems to be in iPhone 5 running iOS 8.

**Comment by NITEMAN** [comment]
Aditional data, it seems to happen only in Facebook's in-app browser

**Comment by capynet** [comment]
I tested on native IOS devices and cant find this error... What's the url?

**Comment by capynet** [comment]
Closing this issue. cant reproduce. On iphone works well :)
