### ISSUE TITLE
Add CallToAction to propose sessions

### ISSUE THREAD

**Issue by DavidHernandez** [AsociacionDrupalES/DrupalCampEs#75]
We need to increase the number of proposed sessions. Adding a block on the sidebar, for sessions might help. Other solutions are welcome.

**Comment by capynet** [comment]
Text: "Propón tu sesión aquí"  /  "Propose your session here". Can be in two lines.

Decorate with strong colors

**Comment by DavidHernandez** [comment]
We can park this one for now, as the call 4 papers is over. But will be nice to have in the future.

**Comment by DavidHernandez** [comment]
This is no longer necessary for this year's camp as the Call4Papers is over.
