### ISSUE TITLE
Add the Individual sponsors to the sponsors page

### ISSUE THREAD

**Issue by DavidHernandez** [AsociacionDrupalES/DrupalCampEs#79]
We are not listing the individual sponsors on the sponsors page. We need to add a view listing them. This is high priority, as we say we will do it, in the sponsors information: http://2015.drupalcamp.es/es/drupalcamp-spain-2015/sponsors/patrocinios

**Comment by jsbalsera** [comment]
Must the listing appear on the sponsor page? Perhaps they could appear in their own page under the sponsors menu item?

**Comment by DavidHernandez** [comment]
Aren't they sponsors too?

**Comment by jsbalsera** [comment]
They are, that doesn't mean that they must be at the end of the same page necessarily. So I'm asking, must that listing be there?

**Comment by DavidHernandez** [comment]
I think the sponsors page is where it belongs. Are there any reasons to 
put them somewhere else?

The Individual sponsors are listed as any other sponsor: 
http://2015.drupalcamp.es/en/drupalcamp-spain-2015/sponsors/sponsorships

Other years have been shown in the sponsors page too: 
http://2014.drupalcamp.es/sponsors.html

**Comment by DavidHernandez** [comment]
PR #83 from @Saphyel should fix this.

**Comment by DavidHernandez** [comment]
This page has been created in another PR. But there are a few issues.

We need more frontend love:

![sponsors](https://cloud.githubusercontent.com/assets/877002/7345019/7642d720-ecd1-11e4-87a5-590dd1a39758.png)

The title also says "Esponsors". It should be Sponsors or "Patrocinadores" in spanish.

**Comment by DavidHernandez** [comment]
We already have a page, that might or might not be behaving correctly, but at least there is something. I'm removing the High priority label for now.

**Comment by capynet** [comment]
Frontend fixes been made.

**Comment by DavidHernandez** [comment]
This is resolved, so far. I would prefer to have this in the same page as the sponsors, but we can survive without it.
