### ISSUE TITLE
Convertir textfields del formulario de compra en selectboxes

### ISSUE THREAD

**Issue by eurodev** [AsociacionDrupalES/DrupalCampEs#84]
Creo que mejoraría la usabilidad del formulario de compra convertir los textfields en selectboxes[1]. Al mismo tiempo, es probable que nos aumentase la conversión si ya por defecto dejamos preseleccionada una unidad para el ticket que marquemos "por defecto".

Lo que no tengo claro es si tiene sentido incorporarlo al profile de cod, porque si no me equivoco, el formulario de tickets no se crea en la instalación, sino posteriormente en la fase de construcción del sitio :-|

[1] http://2015.drupalcamp.es/es/drupalcamp-spain-2015

**Comment by capynet** [comment]
Hecho
