### ISSUE TITLE
Listado de asistentes al Business Day

### ISSUE THREAD

**Issue by monfranco** [AsociacionDrupalES/DrupalCampEs#85]
Hola,
Falta el listado de asistentes al BDay. Habría que enlazarlo al menú de Business Day con una entrada más que se llame "Asistentes"

Thanks

**Comment by jsbalsera** [comment]
Fixed :-) Can be tested in live.

**Comment by monfranco** [comment]
Presi++

On 24 Apr 2015 22:37, Jesús Sánchez Balsera <notifications@github.com> wrote:
Fixed :-) Can be tested in live.

---

**Comment by monfranco** [comment]
For me, this page is correct (windows + firefox / chrome / explorer and ubuntu + firefox / chrome)
I don't see users below the banners

**Comment by jsbalsera** [comment]
Can you please tell the browser? Becase I doesn't happen to me in Chrome or
Firefox... I'll check the number of tickets as soon as I can

On Mon, Apr 27, 2015 at 11:33 AM, David Hernández <notifications@github.com>
wrote:

> This page needs some frontend love:
> http://2015.drupalcamp.es/es/business-day/asistentes
>
> Some users apper below the sidebar on small screens.
>
> [image: business]
> <https://cloud.githubusercontent.com/assets/877002/7344989/33d826ce-ecd1-11e4-9685-be8d03ac8f1a.png>
>
> The list also show less attendees that the list of tickets sold:
> http://2015.drupalcamp.es/es/admin/conference/2/tickets
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AsociacionDrupalES/DrupalCampEs/issues/85#issuecomment-96584083>
> .
>



-- 
Un saludo!

**Comment by DavidHernandez** [comment]
Maybe this is clearer. Browser and Drupal caches cleared. SO linux, browser, chromium, also happening on Firefox.
 
![business2](https://cloud.githubusercontent.com/assets/877002/7345160/6da2180a-ecd2-11e4-93f0-d9ea6f62408a.png)

**Comment by capynet** [comment]
Front-end fixes been made.
