### ISSUE TITLE
TDC y listado para BoFs

### ISSUE THREAD

**Issue by zekivazquez** [AsociacionDrupalES/DrupalCampEs#86]
Sería necesario definir un TDC para los distintos BoFs que se propongan durante la Camp, así como un listado ordenado en el tiempo (en plan calendario/timetable), y una entrada de menú que enlace con dicho listado.

Los nodos de este tipo deberán ser gestionables únicamente por usuarios administradores, ya que el listado funcionará como una pizarra virtual para los BoF.

**Comment by DavidHernandez** [comment]
As this is the last issue standing on the 2015 milestone, I'm marking it as the highest priority. But I don't see it as a requirement for the camp.

**Comment by DavidHernandez** [comment]
@jsbalsera can we close this issue now?

**Comment by jsbalsera** [comment]
Yep, we can.

On Tue, May 26, 2015 at 10:34 AM, David Hernández <notifications@github.com>
wrote:

> @jsbalsera <https://github.com/jsbalsera> can we close this issue now?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AsociacionDrupalES/DrupalCampEs/issues/86#issuecomment-105445176>
> .
>



-- 
Un saludo!
