### ISSUE TITLE
Lista de sponsors

### ISSUE THREAD

**Issue by monfranco** [AsociacionDrupalES/DrupalCampEs#87]
El listado de sponsors no se distinguen bien los patrocinios. Debemos poner:
1 logos por fila en los patrocinios oro: los logos han de ser más grandes que los plata
3 logos por fila en los patrocinios plata: los logos han de ser más grandes que los bronce
4 logos por fila en los patrocinios bronce.

**Comment by DavidHernandez** [comment]
This is our top priority right now.

**Comment by capynet** [comment]
Alguien ya se encargó de la cantidad de items por fila. solo he cambiado el image style para permitir dimensiones mas adecuadas (grandes) y he cambiado algunos logos por unos de mayor calidad.
