### ISSUE TITLE
Prepare final sessions view

### ISSUE THREAD

**Issue by DavidHernandez** [AsociacionDrupalES/DrupalCampEs#88]
We need to prepare the content of the final sessions and theme it. There is already some code that has been rescued from the last year website: https://github.com/AsociacionDrupalES/DrupalCampEs/tree/master/profiles/cod/modules/custom/session_schedule

This is not the best solution, as it has all the sessions hardcoded into a template, but it can save us a lot of time.

**Comment by DavidHernandez** [comment]
This is our top priority right now

**Comment by carlosreig** [comment]
I take it.

**Comment by capynet** [comment]
@DavidHernandez porfa tu o a quien corresponda echenle un vistazo a la tabla para ver si la info es la que tiene que ir.
En un principio me limité a copiar los datos que había en la hoja de calculo que me pasaste, pero no estoy muy seguro de si los track "ORO 1", "ORO 2" sean los nombres que se quieren poner allí.

En todo caso solo hay que tocar el tpl profiles/cod/modules/custom/session_schedule/session-schedule.tpl.php y tocar el txt que se necesite.

Se puede acceder temporalmente a http://2015.drupalcamp.es/sesiones y ya cuando alguien audite el contenido y le de el ok lo pasamos a donde corresponde.

NOTA: los colores no son los definitivos y me falta la versión mobile que espero poder hacer todo eso mañana. No se asusten por el arco iris.

**Comment by capynet** [comment]
Terminado. se puede ver en /schedule (por el menu en Sessions > Calendario de sesiones)
