### ISSUE TITLE
Fix frontpage theming

### ISSUE THREAD

**Issue by DavidHernandez** [AsociacionDrupalES/DrupalCampEs#89]
On the frontpage, the theming doesn't show the same result as an individual node page.

For example: http://2015.drupalcamp.es/

The new about the published sessions, doesn't show the <ul> dots, meanwhile the node does it: http://2015.drupalcamp.es/es/news/%C2%A1v%C3%A1monos-que-nos-vamos-con-las-charlas-drupaleras

**Comment by capynet** [comment]
No se si entendí exactamente lo que hace falta, pero he retocado los links de "ver mas" en la home.
