### ISSUE TITLE
Disable Propose A Session menu-link

### ISSUE THREAD

**Issue by NITEMAN** [AsociacionDrupalES/DrupalCampEs#90]
Because C4P has ended

**Comment by fran** [comment]
Yo me encargo.


On Thu, Apr 30, 2015 at 6:12 PM, Pedro González Serrano <
notifications@github.com> wrote:

> Because C4P has ended
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AsociacionDrupalES/DrupalCampEs/issues/90>.
>



-- 
Francisco José Seva Mora

**Comment by fran** [comment]
Ya estaba quitado en español, yo lo he quitado en la versión en inglés.


On Thu, Apr 30, 2015 at 6:21 PM, Francisco José Seva Mora <
franciscojseva@gmail.com> wrote:

> Yo me encargo.
>
>
> On Thu, Apr 30, 2015 at 6:12 PM, Pedro González Serrano <
> notifications@github.com> wrote:
>
>> Because C4P has ended
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/AsociacionDrupalES/DrupalCampEs/issues/90>.
>>
>
>
>
> --
> Francisco José Seva Mora
>



-- 
Francisco José Seva Mora

**Comment by fran** [comment]
Done!
