### ISSUE TITLE
Error al editar un item de menu

### ISSUE THREAD

**Issue by fran** [AsociacionDrupalES/DrupalCampEs#91]
When user try to edit an item menu, the system shows the following error:

![selection_723](https://cloud.githubusercontent.com/assets/14607/7451736/7102b108-f254-11e4-87e7-29abcf4ab746.png)

**Comment by fran** [comment]
The bug just happen in Live, in DEV is working right now.

**Comment by fran** [comment]
Just happen in my browser :s 
Remove the high priority tag.

**Comment by capynet** [comment]
Cant reproduce. it seems work fine right now.
