### ISSUE TITLE
Promote gold sponsors in the schedule page

### ISSUE THREAD

**Issue by DavidHernandez** [AsociacionDrupalES/DrupalCampEs#97]
Currently, the schedule page has no sidebar: http://2015.drupalcamp.es/es/schedule

This means, we lose the gold sponsors block that should be in every page.

We need to add it back. It can be done adding the sidebar back to the page, adding a block on the top of the page, replacing the silver sponsors block or adding it above the silver's block. Any other ideas are also welcome.

**Comment by NITEMAN** [comment]
Also I think Forcontu is getting too much visibility with the course, hope we can rename it

**Comment by DavidHernandez** [comment]
We can rename the Forcontu course as "Drupal introduction course"

**Comment by capynet** [comment]
Como se habló en el chat de #drupal-es, vamos a dejar el sidebar de lado y en su lugar vamos a poner un bloque con los sponsor gold por arriba o debajo. Con esto quedaría cerrado el issue.

**Comment by capynet** [comment]
Implementado.
